name: Zappa Deployment

on:
  push:
    branches:
      - main   # Trigger this action on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change this to another OS if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set the Python version for your Lambda function

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy with Zappa
      run: |
        source venv/bin/activate
        if zappa status dev; then
          echo "Zappa deployment exists, running update..."
          zappa update dev  # Update the existing deployment
        else
          echo "Zappa deployment does not exist, running deploy..."
          zappa deploy dev  # Deploy a new app
        fi
