name: Zappa Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install flask
        pip install -r requirements.txt
        pip install zappa

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Conditional Zappa Undeploy
      run: |
        source venv/bin/activate
        echo "Checking config.json for undeploy flag..."
        DELETE=$(python3 -c "import json; print(json.load(open('config.json'))['delete_deployment'])")
        echo "Delete setting: $DELETE"
        if [ "$DELETE" = "True" ] || [ "$DELETE" = "true" ]; then
          echo "Deleting Zappa deployment..."
          zappa undeploy dev -y
        else
          echo "Skipping undeploy. Config flag is false."
        fi

    - name: Deploy with Zappa
      run: |
        source venv/bin/activate
        if zappa status dev; then
          echo "Zappa deployment exists, running update..."
          zappa update dev
        else
          echo "Zappa deployment does not exist, running deploy..."
          zappa deploy dev
